sudo: required

addons:
  apt:
    packages: haveged

services:
  - docker

language: ruby

rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"

gemfile:
  - "gemfiles/rails_4.2.gemfile"
  - "gemfiles/rails_5.0.gemfile"
  - "gemfiles/rails_5.2.gemfile"
  - "gemfiles/rails_6.0.gemfile"

env:
  - CASSANDRA_VERSION=2.2
  - CASSANDRA_VERSION=3.0
  - CASSANDRA_VERSION=3.11

script: script/ci-unit-test

bundler_args: "--without=debug"

matrix:
  exclude:
