name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        rails:
          - "6.0"
          - "6.1"
          - "7.0"
          - "7.1"
        scylladb:
          - "4.3.6"
          - "4.4.3"
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / ScyllaDB ${{ matrix.scylladb }}
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker run --name my_scylla_container -d -p 9042:9042 scylladb/scylla:${{ matrix.scylladb }}
          sleep 30
      - run: |
          bundle exec rake test
        env:
          RAILS_ENV: test
