name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        rails:
          - "6.0"
          - "6.1"
          - "7.0"
          - "7.1"
        cassandra:
          - "2.2"
          - "3.0"
          - "3.11"
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Cassandra ${{ matrix.cassandra }}
    services:
      cassandra:
        image: cassandra:${{ matrix.cassandra }}
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'SHOW VERSION' localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          bundle exec rake test
        env:
          RAILS_ENV: test
